### ISSUE TITLE
Change the error with notary when repository does not exist.

### ISSUE THREAD

**Issue by diogomonica** [docker/notary#464] opened 2016-01-15 21:29 UTC
Right now doing a notary list returns a "unable to reach trust server", which it should probably return something different.

```
➜    notary list docker.io/diogomonica/noexist -s https://notary.docker.io
* fatal: unable to reach trust server at this time: 401.
```

**Comment by cyli** [comment] 2016-01-19 18:15
@diogomonica `"unauthorized to access <repo> at this <trust server>"`?

**Comment by diogomonica** [comment] 2016-01-21 19:25
```
➜  notary git:(master) ✗ bin/notary list docker.io/diogomonica/noexist -s https://notary.docker.io -v
DEBU[0000] Using the following trust directory: /Users/diogo/.docker/trust
ERRO[0000] could not reach https://notary.docker.io: 401
INFO[0000] continuing in offline mode
DEBU[0000] Failed to initialize PKCS11 environment: loaded library /usr/local/docker-experimental/lib/libykcs11.dylib, but no HSM slots found
DEBU[0000] Adding cert with certID: 89451573604cf609dc0996402307f8600cf5377fb7b8e8a7ca71722f7d4452a6
DEBU[0000] Adding cert with certID: 3b57267eb124e8284c1519f7ba45bb51077dea1c77c0a0e8012fd93798243a58
DEBU[0000] Adding cert with certID: a2489bcac7a79aa67b19b96c4a3bf0c675ffdf00c6d2fabe1a5df1115e80adce
DEBU[0000] Adding cert with certID: c6b86f21ae272f3ae27b8da8a5762df97f09d6d0604ab49dd1d9920c6e25b65b
DEBU[0000] Adding cert with certID: ff544c7f4ffa0a61b2fb836fb581182181c971acd58a7023c9a3b049dc952edd
DEBU[0000] Adding cert with certID: 7d3f80542c5d3bb761551e7601426be803e4cc0a0269a6bf796718978743cd5b
* fatal: client is offline
```

We need to distinguish the 401 case from everything else.

**Comment by riyazdf** [comment] 2016-01-25 19:47
With #486 we're back to:

```
➜    notary list docker.io/diogomonica/noexist -s https://notary.docker.io
* fatal: unable to reach trust server at this time: 401.
```

**Comment by endophage** [comment] 2016-01-27 02:04
Closing as a "won't fix" for the below reasons:

This is a dupe of #286 and to some extend #287 (they all happen for the same reason).

We now have some additional logic around failures of the original /v2/ ping, but this is an error that I don't believe we can solve in the client. The behaviour of the token server is identical in the cases that:

1. The repo exists but you aren't authorized to read it.
2. The repo does not exist. 

In both these cases the token server simply refuses to issue a token. Without a token, the server will always respond with a 401. I believe the reasoning is that if we sometimes returned a 404, it might leak information about which repos don't exist, vs. which do and you're not authorized.

Whether that information leakage is important is a different discussion but is highly relevant to this.

**Closed by endophage** 2016-01-27 02:04 UTC
Labels: bug
