### ISSUE TITLE
Support stricter policy than the current automatic/silent TOFU

### ISSUE THREAD

**Issue by mtrmac** [docker/notary#399] opened 2016-01-04 15:27 UTC
Currently, the Notary trust design:

* Uses the first HTTPS connection to a Notary server as a starting point. However strong the subsequent TUF multi-signature/key rollover mechanisms may be, this initial trust establishment is subject to whims and compromises of any of the ~650 public TLS CAs. The Docker Hub might avoid this issue by pinning a Docker certificate for that server, but this does not help for any of the other (ISV-specific or internal data-center-specific) registries and Notary servers.
* Treats signature by anyone and any key equally, as long as they are the first key seen for that repository and the Notary server serves that signature. But not every image on the Internet is equally useful, desirable or secure, signed or not; and it should not be necessary to trust the Notary servers that they will only serve signatures by the “expected” owner of a particular repository (and in the case of the public Docker Hub it is fairly difficult to define “expected” rigorously, see the difficulties web browser security has with various misspellings of paypal.com).

So, we need to support configuration of clients / the signature verification mechanism with preloaded roots of trust:
* At the very least, it should be possible to pre-load a set of public root keys for a specific repository; this would make it unnecessary to trust both the CA ecosystem and the Notary server.
* It would be very useful to support also pre-loading a set of public root keys applicable to a namespace ($hostname/redhat/*), or perhaps applicable to a whole registry: Larger software vendors can commit to a set of root keys to be used within the next several years, but do not know the names of products that will be shipped within that time frame, so only a per-repository mechanism would require a manual step before installing any of the products, but a per-namespace or per-registry mechanism would be future-proof in this sense.
* Finally, we need an option to refuse signatures from any author which has not been preconfigured (or from any repository which has not been preconfigured with specific root keys, which is ~equivalent): whatever the company policy says, it is currently too easy for a junior developer to google “Docker image for $use_case”, download that image and base further work on it, however insecure or unmaintained the first Google result of that search is.

The implementation of this will probably have much in common with #395, but #395 focuses on *existence* of  mandatory verification and using consistent mechanisms; this issue focuses on *what* the mandatory and consistent mechanism should support.

**Comment by mtrmac** [comment] 2016-01-04 15:27
(I have noticed that there has been recent work on TUF delegations, which may be relevant, but I have not yet had time to catch up with that work.)

**Comment by endophage** [comment] 2016-01-04 19:08
I don't think the delegation work is particularly relevant to this problem.

Using a configuration file with the `notary -c config.json` already allows you to specify a root CA which will be solely trusted. It would be good to make this more flexible such that multiple CAs may be specified (maybe by allowing a directory to be configured with all CAs in the dir being trusted). That might be a more appropriate issue to file.

**Comment by cyli** [comment] 2016-01-05 01:23
Is this a duplicate of description of https://github.com/docker/notary/issues/342?  If so, should we merge the two issues?

**Comment by mtrmac** [comment] 2016-01-05 12:12
> Using a configuration file with the notary -c config.json already allows you to specify a root CA which will be solely trusted. It would be good to make this more flexible such that multiple CAs may be specified (maybe by allowing a directory to be configured with all CAs in the dir being trusted).

* This would be better than nothing, but we can make it stronger: an user using Docker Hub images, RHEL images from Red Hat, and application images from another ISV could configure the system for the three relevant CAs, getting most of the 650 CAs out of the picture, but such a configuration would still not prevent e.g. the ISV from attacking Docker Hub or RHEL repositories. Pinning specific trusted CAs for individual repositories would prevent cross-repository attacks.

* (This is basically the “what is the trust model and assumptions” question I’ve been pestering people with.) I don’t think the notary server CAs are the private keys in which we should be putting ultimate trust; rather, the users should be worrying about, and pinning, the TUF root keys:

 * For the Docker Hub, there is necessarily a single CA for all repositories hosted there; this makes it impossible to treat individual repositories, or namespaces of repositories, hosted on the Docker Hub, differently (e.g. only allowing use of a subset of repositories hosted on the Docker Hub, or pinning keys for specific repositories and their individual authors).

 * For off-line mirrors (#398), the notary server mirror (whether a live server or a static HTTP server) will be using HTTPS and a CA, but the CA will necessarily be different from the CA used by the primary public registry/notary (the mirror operator usually won’t have access to the public servers’ private keys). It would still be desirable to place trust in the public key of the actual author of the images, so that even the off-line data center could directly rely on the image authors’ signatures without also having to trust the mirror or some kind of re-signing mechanism, and so that the trust bootstrapping configuration could be the same on the public internet and in the off-line sites.

 * (The TUF design generally assumes no trust in the signature storage and transfer mechanism; all security is internal to TUF and its multi-signatures. So it seems to be closest to the “spirit of TUF” to worry about root keys rather than Notary servers and HTTPS. OTOH, to be fair, TUF does not deal with the bootstrapping problem at all.)

**Comment by mtrmac** [comment] 2016-01-05 12:15
> Is this a duplicate of #342? If so, should we merge the two issues?

This is a superset of #342: #342 only asks for disabling TOFU, this also refers to a trust bootstrap/pinning mechanism for individual repositories (which #342 seems to assume will happen manually), and probably also a similar mechanism for whole registries and registry namespaces.

Would you prefer a single several-subtasks issue like this, or a larger number of smaller ones?

**Comment by dnwake** [comment] 2016-04-08 21:37
It would be a valuable feature of Docker Content Trust if users could be confident in the integrity of images based solely on a public key published by the image's creator, **even if neither the Registry nor the Notary server were trusted**.  In order to do this, users would need the ability to import known good public keys and disable silent acceptance of TOFU.

**Comment by endophage** [comment] 2016-04-08 21:39
@dnwake that is the purpose of this PR that is approaching completion: https://github.com/docker/notary/pull/624

**Comment by riyazdf** [comment] 2016-04-19 20:51
Closing this issue since #624 has been merged, which allows for disabling TOFU and whitelisting cert IDs/CAs

**Closed by riyazdf** 2016-04-19 20:51 UTC
