### ISSUE TITLE
Issues Setting Up Notary Server

### ISSUE THREAD

**Issue by sabada** [docker/notary#937] opened 2016-08-31 23:30 UTC
I am trying to set up my own notary server, but I run into the error "x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "notary-server")"

I have been following the guidelines suggested in the docs, and have generated my own keys and certificates using the following command: 
`openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout notary-server.key -out notary-server.crt`

I am also using the following config.json on my notary-server

```
{
  "server": {
    "http_addr": ":4443",
    "tls_key_file": "./server.key",
    "tls_cert_file": "./server.crt"
},
  "trust_service": {
    "type": "remote",
    "hostname": "notary-signer",
    "port": "7899",
    "tls_ca_file": "./root-ca.crt",
    "key_algorithm": "rsa",
    "tls_client_cert": "./notary-server.crt",
    "tls_client_key": "./notary-server.key"
},
  "storage": {
    "backend": "memory" 
}
}
```

Any help would be appreciated, thank you!

**Comment by riyazdf** [comment] 2016-08-31 23:43
Hi @sabada, could you please post more logs from notary-server and notary-signer so we can get a better idea of where exactly you're experiencing this failure?  Also, what are you using for your notary signer config?

One things that jumps out as I'm reading through this is that the cert/key generation command you pasted generates a self-signed cert, and that may not line up against a different `./root-ca.crt` to verify against when checking the certificate chain.
Also, is there any reason why you're using different certs and keys for `tls_cert_file` and `tls_client_cert`?

I'd recommend taking a look at the config docs ([server](https://docs.docker.com/notary/reference/server-config/) and [signer](https://docs.docker.com/notary/reference/signer-config/)) for more information about these configs and some samples

**Comment by HuKeping** [comment] 2016-09-01 01:37
Hi @sabada could you please also try 
```
openssl verify notary-server.crt
```
to see if you have already installed the cert to your system cert bundle.

I think this might be  much more like a cert issue than notary.

**Comment by sabada** [comment] 2016-09-01 17:49
Thanks for the response, it does seem like it is some cert issue as the logs for notary-server tell me 
`2016/09/01 17:43:03 http: TLS handshake error from 172.18.0.1:55268: remote error: bad certificate`

and the last log for notary-signer is telling me the version number and git commit
`{"level":"info","msg":"Version: 0.3, Git commit: a9b2b95","time":"2016-09-01T17:42:47Z"}`

I did fix up my config files to match the config docs and am now using the same certs and keys for `tls_cert_file` and `tls_client_cert` but am now getting a different error

`x509: certificate signed by unknown authority (possibly because of "asn1: structure error: length too large" while trying to verify candidate authority certificate "notary-server”)`

The certs were not installed before, but I made sure they are installed now

**Comment by riyazdf** [comment] 2016-09-01 20:37
@sabada `x509: certificate signed by unknown authority` means that the specified root CA does not properly chain to the leaf certificate presented.

It would be helpful to us if you could describe when you're hitting this failure -- is this when starting the notary server and signer containers, or when trying to connect with a notary client?

If it's when the client is trying to connect to a notary server: you'll have to make sure that the client is not restricting which root CA it trusts.  This issue walks through how to resolve that: https://github.com/docker/notary/issues/935

If it's when trying to setup the notary server and signer: What are you using for the `"tls_ca_file"` configuration?  If you're self-signing a new certificate, the provided `root-ca.crt` fixture will not chain to that certificate, and so you'll have to specify the self-signed certificate instead to be valid.  And likewise, what are you using for the `client_ca_file` field in the signer configuration?

**Comment by sabada** [comment] 2016-09-01 21:12
I believe there is a problem when the client is trying to connect to a notary-server since the issue is occurring while I am trying to do a docker push. I also just tried for first time running online commands like notary list, and I get `fatal:client is offline`

My config files are listed below, and I am pointing it to my created cert files. 

notary-server config file
```
{
  "server": {
    "http_addr": ":4443",
    "tls_key_file": "./notary-server.key",
    "tls_cert_file": "./notary-server.crt"
  },
  "trust_service": {
    "type": "remote",
    "hostname": "notarysigner",
    "port": "7899",
    "tls_ca_file": "./root-ca.crt",
    "key_algorithm": "rsa",
    "tls_client_cert": "./notary-server.crt",
    "tls_client_key": "./notary-server.key"
  },
  "storage": {
    "backend": "memory"
  }
}
```

notary-signer config file
```
{
  "server": {
    "http_addr": ":4444",
    "grpc_addr": ":7899",
    "tls_cert_file": "./notary-signer.crt",
    "tls_key_file": "./notary-signer.key",
    "client_ca_file": "./notary-server.crt"
  },
  "storage": {
    "backend": "memory"
  }
}
```

notary cli config file
```
{
        "trust_dir" : "~/.docker/trust",
        "remote_server": {
                "url": "https://notary-server:4443",
                "root_ca": "./root-ca.crt"
        }
}
```

**Comment by riyazdf** [comment] 2016-09-01 21:23
Ok thanks!  Just to check: you're running with `DOCKER_CONTENT_TRUST=1` and `DOCKER_CONTENT_TRUST_SERVER=<url_to_your_server>` right?  And also, you aren't getting any errors in the server/signer logs before you try to contact them with a `notary` or `docker` command?

If so, it seems like the issue is indeed related to #935 - your notary CLI is trying to trust `./root-ca.crt` as the root CA for the notary server -- but if you're using a self-signed `notary-server.crt` then you won't have a valid chain of trust between the desired CA that the client is pinning to and the certificate that notary server is presenting to the CLI.

Could you try changing the `remote_server.root_ca` field in your notary cli config file?  You can try testing with `notary -D list` (`-D` is the debug flag)

**Comment by sabada** [comment] 2016-09-01 21:36
So I have set `DOCKER_CONTENT_TRUST=1` and `DOCKER_CONTENT_TRUST_SERVER=https://notary-server:4443` and the logs look fine until I get the TLS handshake error. I am a little confused on what I should be changing the `remote_server.root_ca` to. 

Currently when i run `notary -D list` this is the output

```
DEBU[0000] Using the following trust directory: /home/ubuntu/.docker/trust 
DEBU[0000] Trusting 1 certs                             
ERRO[0000] could not reach https://notary-server:4443: Get https://notary-server:4443/v2/: x509: certificate signed by unknown authority 
INFO[0000] continuing in offline mode                   
DEBU[0000] Failed to initialize PKCS11 environment: no library found 

* fatal: client is offline
```

**Comment by riyazdf** [comment] 2016-09-01 21:49
If you have the server certificate in your trusted system certificates, you can just try removing that value altogether, such that your config looks like:

```
{
        "trust_dir" : "~/.docker/trust",
        "remote_server": {
                "url": "https://notary-server:4443"
        }
}
```

You could also try setting it to `notary-server.crt`, if you'd prefer

**Comment by cyli** [comment] 2016-09-01 21:51
Also, just to be certain we understand how everything is laid out in your FS, and what the files look like:

1.  The self-signed `root-ca.crt` was something that you generated, and that root key was used to sign your own `notary-server.crt` and `notary-signer.crt`?  And your own `root-ca.crt` is in the same directory as your client config file?  (the paths for each config file are relative to your config file)
2. `notary-server.crt` and `notary-signer.crt` both include the root CA cert as well as the server certs?

**Comment by cyli** [comment] 2016-09-01 21:55
@sabada oops, sorry, @riyazdf just pointed out to me that the openssl command above doesn't generate a root CA cert.  In which case he is totally correct and if there is no root CA, it should be removed from the config.  :)

**Comment by sabada** [comment] 2016-09-01 22:09
Thanks! So now I am not getting any errors when running `notary -D list` but the docker push is still giving me the same error. 

When I run `docker -D push` this is what I get:
```
Signing and pushing trust metadata
DEBU[0002] reading certificate directory: /home/ubuntu/.docker/tls/notary-server:4443 
DEBU[0002] crt: /home/ubuntu/.docker/tls/notary-server:4443/root-ca.crt 
DEBU[0002] Error pinging notary server "https://notary-server:4443/v2/": Get https://notary-server:4443/v2/: x509: certificate signed by unknown authority 
DEBU[0002] Failed to initialize PKCS11 environment: no library found 
x509: certificate signed by unknown authority
```

Is the notary client connecting fine? There is still nothing else in the logs other than the TLS handshake error

**Comment by riyazdf** [comment] 2016-09-01 22:31
@sabada: glad to hear that notary's working now!

The notary CLI config is only used for the `notary` commands.  For docker commands you'll need to add `notary-server.crt` to `.docker/tls/notary-server:4443` as `ca.crt`

**Comment by sabada** [comment] 2016-09-01 22:35
Thank you so much for all your help! I was able to push now and everything seems to be working fine!!!

**Comment by riyazdf** [comment] 2016-09-01 22:59
glad it's all working!  Closing this issue, but please feel free to re-open this issue if you run into more cert-related config problems :)

**Closed by riyazdf** 2016-09-01 22:59 UTC

**Comment by sabada** [comment] 2016-09-12 18:08
Hi, not sure if this should be an new issue or not, but now I have moved to instead having notary-server and notary-signer started from the same machine to different servers. I am able to get them up and running and connecting to each other but I run into some certificate errors. 

On notary-signer, the logs say 
`2016/09/12 17:55:48 grpc: Server.Serve failed to complete security handshake from "172.31.33.193:54133": remote error: bad certificate`

And on notary-server the logs say
`{"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority\"","time":"2016-09-12T17:51:24Z"}`

I am using the same config files that I used when I got it to work on the same machine, but changed the hostname and such to point to the new location for notary-signer. 

Any thoughts on why I am now getting this error?

**Comment by cyli** [comment] 2016-09-12 18:22
@sabada Did you also change the hostname (or add the host where notary server is running as a SAN) on the notary-signer certificate?

**Comment by sabada** [comment] 2016-09-12 19:39
The only thing I changed was the hostname in the server configuration. Looking at the different config docs that @riyazdf linked above, I did not see anything in the signer configuration regarding the host for the notary server. Where would I configure that?

**Comment by riyazdf** [comment] 2016-09-12 19:46
@sabada can you check what the values are for the CNs and SANs (Subject Alternative Names) of the certificates you're using for `notary-server.crt` and `notary-signer.crt`?

@cyli and I are hypothesizing that the new location of the notary server/signer is not being reflected in these values, which would make the certificate invalid for the TLS connection.  Reusing the same notary configurations we discussed above with the different hostnames should work, provided that the certificates are also valid.

You can use `openssl x509 -in notary-server.crt -noout -text` to check this

**Comment by sabada** [comment] 2016-09-12 19:49
Oh yea, so when I made the certificates the first time, i used notary-server as the CN for the server and then notary-signer for the signer. 

Now I use the hostname of my server for the server certificate, and signer for the signer certificate. I don't know about the SANs though as I don't see any mention regarding that.

**Comment by riyazdf** [comment] 2016-09-12 20:00
@sabada: what are you using for your CA files for server and signer (`tls_ca_file` and `client_ca_cert`)?  Is it possible that the CAs you're using are not in sync with your new certificates?

**Comment by sabada** [comment] 2016-09-12 20:06
So this is my signer-config
```
{
  "server": {
    "http_addr": ":4443",
    "tls_key_file": "./notary-server.key",
    "tls_cert_file": "./notary-server.crt"
  },
  "trust_service": {
    "type": "remote",
    "hostname": "ec2-52-42-174-34.us-west-2.compute.amazonaws.com",
    "port": "7899",
    "tls_ca_file": "./root-ca.crt",
    "key_algorithm": "rsa",
    "tls_client_cert": "./notary-server.crt",
    "tls_client_key": "./notary-server.key"
  },
  "storage": {
    "backend": "memory"
  }
```

and this is my server config
```
{
  "server": {
    "http_addr": ":4444",
    "grpc_addr": ":7899",
    "tls_cert_file": "./notary-signer.crt",
    "tls_key_file": "./notary-signer.key",
    "client_ca_file": "./notary-server.crt"
  },
  "storage": {
    "backend": "memory"
  }
```

I am using the same certificates on both servers.

**Comment by riyazdf** [comment] 2016-09-12 20:18
In your (top) server config, `tls_ca_file ` should not be `root-ca.crt` if you're using a self-signed `notary-signer.crt`.  Did you generate `root-ca.crt`?

Can you try specifying `./notary-signer.crt` for that value?

**Comment by sabada** [comment] 2016-09-12 20:28
Oh wow, okay so I think that might have been it. Now the log for the server is just `{"level":"info","msg":"Version: 0.3, Git commit: 930168f","time":"2016-09-12T20:27:21Z"}` and no more logs indicating that certificate error. Is that the expected output for the logs?

**Comment by riyazdf** [comment] 2016-09-12 20:30
awesome.  That should be it if everything is working :)

**Comment by sabada** [comment] 2016-09-12 20:31
Thank you so much again! I didn't have that for my other setup. Does that mean I don't need root-ca.crt at all?

**Comment by riyazdf** [comment] 2016-09-12 21:00
Not a problem, glad everything is working!  You shouldn't need `root-ca.crt` in your other setup either if you're also using self-signed certs -- it probably worked if you added the server/signer certs to your system's trusted certificate pool.

**Comment by sabada** [comment] 2016-09-12 21:24
That's probably it haha. Well everything is working now, so thank you once again!

**Comment by abhi-dwivedi** [comment] 2019-03-19 12:07
hi can i configure the notary server with https
like http://notary-server:8080
