### ISSUE TITLE
Broken svg images

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#679] opened 2016-04-13 11:00 UTC
Does it only the problem of my browser? All the svg links are broken, include:
- https://github.com/docker/notary/blob/master/docs/service_architecture.md
- https://github.com/docker/notary/blob/master/docs/running_a_service.md#high-availability

**Comment by cyli** [comment] 2016-04-13 16:13
@hukeping no, it's because GitHub won't display relative links to acts in their viewer.   See https://github.com/isaacs/github/issues/316

We can fix it if we link to cdn.rawgit.com instead, but that also affects the doc builder (these docs also produce the content for https://docs.docker.com/notary).

So not entirely sure what to do.  Ideally something would substitute the relative links back in when we do the doc building.  cc @moxiegirl

**Comment by HuKeping** [comment] 2016-04-14 09:53
Thanks @cyli , I think we can just wait since it's the problem of GitHub

**Comment by moxiegirl** [comment] 2016-04-18 18:25
@cyli you ok with closing this?

**Comment by cyli** [comment] 2016-04-18 18:50
@moxiegirl If we can't modify the doc script to do the replacement, sure.  I mainly wanted to check with you to see if modifying the makefile in the docs directory to be able to do that would propagate the change to the doc releases on docker?

**Comment by moxiegirl** [comment] 2016-04-18 19:21
@cyli  The `docs` directory content is intended for release on docs.docker.com and not to be read in place on github.com.  We've been keeping the build scripts uniform across all the numerous Docker repositories because managing different local build scripts is a burden to the Docs team.  I've gone back to being an individual contributor.  Your best bet is to talk to Patrick N. for a decision regarding this.

**Comment by endophage** [comment] 2016-04-19 17:59
We're going to update to the absolute rawgit.com urls. We've confirmed the service is meant to be used in production settings and it will make the diagrams show up consistently between github.com and docs.docker.com

**Closed** 2016-04-19 20:49 UTC
