### ISSUE TITLE
migrate.sh: '/usr/bin/env sh' and bash syntax fails on Ubuntu

### ISSUE THREAD

**Issue by karstengr** [docker/notary#1101] opened 2017-02-17 08:06 UTC
When running migrate.sh in an Ubuntu based image it fails because '/usr/bin/env sh' is set and bash syntax [[ ]] is used.
@cyli This was introduced by the following commit:
https://github.com/docker/notary/commit/a021d16392aeafe324ef070cff7818e1c6b3fb4b#diff-6fda77e83f644ffce9653131ef0d74f3R1

**Comment by endophage** [comment] 2017-02-17 22:05
Duplicate of https://github.com/docker/notary/issues/1063

**Closed by endophage** 2017-02-17 22:05 UTC
Labels: Duplicate
